"""empty message

Revision ID: 30ae48703361
Revises: 40b8b3be959d
Create Date: 2023-02-23 18:08:14.826618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ae48703361'
down_revision = '40b8b3be959d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('company_cif',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('telephone_number',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.alter_column('telephone_number',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('company_cif',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
