"""empty message

Revision ID: 5b15c5513819
Revises: 8a508695f5b1
Create Date: 2023-01-26 17:16:26.453096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b15c5513819'
down_revision = '8a508695f5b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('company_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('url_image', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(length=250), nullable=False))

    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('url')
        batch_op.drop_column('url_image')
        batch_op.drop_column('price')
        batch_op.drop_column('company_name')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
