"""empty message

Revision ID: 5e8be5cff151
Revises: a17e7d5c79e4
Create Date: 2023-01-18 20:53:40.958885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8be5cff151'
down_revision = 'a17e7d5c79e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
