"""empty message

Revision ID: 724481a244f5
Revises: f352708b38a4
Create Date: 2023-01-11 18:45:03.638160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724481a244f5'
down_revision = 'f352708b38a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login')
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('url_image', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint(None, ['company_name'])

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=250), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_constraint('supplier_id_login_fkey', type_='foreignkey')
        batch_op.drop_column('id_login')
        batch_op.drop_column('city')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_constraint('user_id_login_fkey', type_='foreignkey')
        batch_op.drop_column('id_login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_login', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('user_id_login_fkey', 'login', ['id_login'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id_login', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('supplier_id_login_fkey', 'login', ['id_login'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('address')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('url_image')
        batch_op.drop_column('company_name')

    op.create_table('login',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('type_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='login_pkey'),
    sa.UniqueConstraint('email', name='login_email_key')
    )
    # ### end Alembic commands ###
