"""empty message

Revision ID: 911b3392b5ea
Revises: 72d5e998a082
Create Date: 2023-01-31 19:08:09.440816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911b3392b5ea'
down_revision = '72d5e998a082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
