"""empty message

Revision ID: a80bf3c7cf3e
Revises: f113fde3fce9
Create Date: 2023-01-21 11:30:31.258356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80bf3c7cf3e'
down_revision = 'f113fde3fce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_constraint('offer_company_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.create_unique_constraint('offer_company_name_key', ['company_name'])

    # ### end Alembic commands ###
