"""empty message

Revision ID: bb5e94878a0d
Revises: 335973101805
Create Date: 2023-01-13 14:55:22.305506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5e94878a0d'
down_revision = '335973101805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=250), nullable=False))
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
