"""empty message

Revision ID: f550879867d2
Revises: 431621ccbe20
Create Date: 2023-01-14 00:31:12.878995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f550879867d2'
down_revision = '431621ccbe20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('supplier_city_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'city', ['city_id'], ['id'])
        batch_op.drop_column('city')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('user_city_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'city', ['city_id'], ['id'])
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_city_fkey', 'city', ['city'], ['name'])
        batch_op.drop_column('city_id')

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('supplier_city_fkey', 'city', ['city'], ['name'])
        batch_op.drop_column('city_id')

    # ### end Alembic commands ###
